### ISSUE TITLE
entering user credentials in login page throws error?

### ISSUE THREAD

**Issue by sridhar1982** [mariubog/oauth-client-sample#4]
Q1:

when I access `http://localhost:8005/authorized-results`, I am redirected to `http://localhost:8005/login` and a login page shows up.

I entered `roy` and `spring`  but I get `bad credentials`. why is it so?

------------

Q2:

In this file https://github.com/mariubog/oauth-client-sample/blob/master/src/main/java/oauth/client/demo/MyRestController.java, you commented the following:

```java
/**
	 * User is being redirected to login page for required authorization This
	 * uri REQUIRES authentication on client side
	 * 
	 * 
	 * 	if you want to set username and password for your template you can still do it here 
	 * 	but you have to obtain username and password from the user 
	 * 	
	 * 	if (restTemplate.getResource() instanceof ResourceOwnerPasswordResourceDetails) {
	 * 		((ResourceOwnerPasswordResourceDetails) restTemplate.getResource()).setUsername(username);
	 * 		((ResourceOwnerPasswordResourceDetails) restTemplate.getResource()).setPassword(password);
     * 
	 * 	}
	 * 	
	 * 	in the rest template that is used in this example it is hard coded in the resource 
	 * 	details here @see {@link OauthClientConfig#fullAccessresourceDetails(String)}
	 * 		
	 */
	@RequestMapping(value = "/authorized-results")
	@ResponseBody
	public Map authorized() throws Exception {
 
		return oauthConnectionService.getResults(userResourceUrl, Map.class, restTemplate);
	}
```

why do the do the following check?

`if (restTemplate.getResource() instanceof ResourceOwnerPasswordResourceDetails) {`

since the restTemplate used here is the `myRestTemplate` bean which is configured already with `ResourceOwnerPasswordResourceDetails`

https://github.com/mariubog/oauth-client-sample/blob/master/src/main/java/oauth/client/demo/config/OauthClientConfig.java

-------------

Thanks

**Comment by mariubog** [comment]
ad2
Well `RestTemplate` interface is being injected so you don't know 100% what resource it is configured with in controller class. You only know it because you configured it, it just loosely coupled and follows common design pattern so you should do this checking to know just in case implementation of `restTemplate` changes.
ad 1
When was the last time you downloaded the copy of this repository, I thought I fixed this problem lf you downloaded it today and still have problem with logging let me know. I just don't have an access to this project now, if problem persists I ll  look at it tomorrow. Sorry for the inconvenience.

**Comment by sridhar1982** [comment]
I downloaded the latest copy of this repository.  I still have problem with log-in. kindly help with the issue
